### PR TITLE
Added reloadable English() example for inventory counting

### PR DESCRIPTION
**Pull request by olegzd**
Added an example of reusing the English() object through using module reloading. On top of that, added an example of determining inventory counts for a few test sentences, and the way to interact with Doc objects, finding wether they're a noun with descriptive compound objects ('fresh ground beef' VS 'beef')

### CODE REVIEW

**Comment by honnibal** [comment]
Hey,

As I said over email, thanks for this :)

Some binary files seem to have been caught in the commit though. You'll need to get rid of them, and make sure they don't appear in the history. Unfortunately I can't remember how to do this off the top of my head.

**Comment by olegzd** [comment]
> Some binary files seem to have been caught in the commit though.

Whoops! When I forced added to the examples/ folder it included the binary .pyc files in the commit. Updated :)

**Comment by honnibal** [comment]
You've still got a .DS_STORE file in there.

**Comment by olegzd** [comment]
Removed the .DS_Store + added an entry to .gitignore so no one else makes the same mistake.

**Pull request merged**
