### PR TITLE
introduce sentence boundaries for additional root tokens

### PR DESCRIPTION
**Pull request by wbwseeker**
added the one line that @honnibal suggested to fix issue #322

### CODE REVIEW

**Comment by wbwseeker** [comment]
the parser should not get into a loop again.

There is one issue with this way of introducing additional root nodes, and this is serious:
if we have a parse like this: heads [0,-1,-2,-3], deps [ROOT, ROOT, nsubj, nsubj]
arc_eager.finalize_state() will make the second token it's own root and therefore sentence
by changing it to [0,1,-2,-3] with [ROOT, ROOT, nsubj, nsubj]

This is a non-projective structure and the sentence boundary at the second token will
disconnect tokens 2 and 3 from their head 0. This will not be a valid state, but there is currently no mechanism to prevent this. The only reason why this is probably not showing currently is because the statistical model will rarely predict such a structure for proper input.
However, this is something we shouldn't rely on because the model could be used to parse unfamiliar input and will then break on it.

**Comment by honnibal** [comment]
That structure is familiar --- I thought about that when doing the joint segmentation and parsing for speech. I thought I had constraints which prevented this, but obviously not. I'll have a look at this.

**Comment by honnibal** [comment]
Definitely no constraints.

I'll start digging through the history to get a sense of what I was thinking and what options I tried.

**Comment by wbwseeker** [comment]
cool. we should probably merge the pull request already anyway, because the loop bug is currently on the master branch

**Pull request merged**
